# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vBx_DEShSh438RXNSo3d-ZfnJAYT-9ME
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import pickle
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

# Konfigurasi halaman
st.set_page_config(
    page_title="Prediksi Harga Saham BRIS",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Load model dan scaler
@st.cache_resource
def load_model():
    with open('model_cpso.pkl', 'rb') as f:
        model = pickle.load(f)
    with open('scaler_x.pkl', 'rb') as f:
        scaler_x = pickle.load(f)
    with open('scaler_y.pkl', 'rb') as f:
        scaler_y = pickle.load(f)
    return model, scaler_x, scaler_y

model, scaler_x, scaler_y = load_model()

# Judul aplikasi
st.title("📊 Aplikasi Prediksi Harga Saham BRIS")
st.markdown("---")

# Sidebar untuk input parameter
st.sidebar.header("⚙️ Pengaturan")

# Pilihan mode
mode = st.sidebar.radio(
    "Mode Prediksi",
    ["Prediksi Otomatis", "Input Manual"]
)

# Feature columns (harus sama dengan training)
feature_columns = ["Open", "High", "Low", "Close", "Volume"]

# Fungsi untuk mengambil data terbaru
def get_latest_data():
    """Ambil data terbaru dari Yahoo Finance"""
    end_date = datetime.now()
    start_date = end_date - timedelta(days=60)

    data = yf.download("BRIS.JK", start=start_date, end=end_date)
    if isinstance(data.columns, pd.MultiIndex):
        data.columns = data.columns.get_level_values(0)

    data = data.reset_index()
    data['Date'] = pd.to_datetime(data['Date'])

    return data

# Fungsi prediksi
def predict_price(features):
    """Lakukan prediksi harga"""
    features_scaled = scaler_x.transform(features)
    pred_scaled = model.predict(features_scaled)
    pred_price = float(scaler_y.inverse_transform(pred_scaled.reshape(-1, 1)))
    return pred_price

# Main content
if mode == "Prediksi Otomatis":
    st.header("🔮 Prediksi Otomatis")

    with st.spinner("Mengambil data terbaru dari Yahoo Finance..."):
        data = get_latest_data()

    if not data.empty:
        # Tampilkan data terbaru
        st.subheader("📋 Data Historis 10 Hari Terakhir")
        st.dataframe(data.tail(10)[['Date', 'Open', 'High', 'Low', 'Close', 'Volume']].style.format({
            'Open': '{:.2f}',
            'High': '{:.2f}',
            'Low': '{:.2f}',
            'Close': '{:.2f}',
            'Volume': '{:,.0f}'
        }))

        # Ambil data terakhir untuk prediksi
        latest_data = data.iloc[-1]
        features = latest_data[feature_columns].values.reshape(1, -1)

        # Tombol prediksi
        if st.button("🚀 Lakukan Prediksi", type="primary"):
            with st.spinner("Menghitung prediksi..."):
                predicted_price = predict_price(features)
                last_close = latest_data['Close']
                change = predicted_price - last_close
                pct_change = (change / last_close) * 100

                # Tampilkan hasil
                col1, col2, col3 = st.columns(3)

                with col1:
                    st.metric(
                        label="Harga Terakhir",
                        value=f"Rp {last_close:,.2f}",
                        delta=None
                    )

                with col2:
                    st.metric(
                        label="Prediksi Besok",
                        value=f"Rp {predicted_price:,.2f}",
                        delta=f"Rp {change:,.2f}"
                    )

                with col3:
                    st.metric(
                        label="Perubahan",
                        value=f"{pct_change:+.2f}%",
                        delta=None
                    )

                # Visualisasi
                st.subheader("📈 Grafik Prediksi")

                # Buat grafik dengan Plotly
                fig = make_subplots(
                    rows=2, cols=1,
                    subplot_titles=('Data Historis', 'Prediksi'),
                    vertical_spacing=0.1,
                    row_heights=[0.7, 0.3]
                )

                # Plot data historis
                fig.add_trace(
                    go.Scatter(
                        x=data['Date'],
                        y=data['Close'],
                        mode='lines+markers',
                        name='Harga Close',
                        line=dict(color='blue', width=2)
                    ),
                    row=1, col=1
                )

                # Tambahkan titik prediksi
                pred_date = latest_data['Date'] + timedelta(days=1)
                fig.add_trace(
                    go.Scatter(
                        x=[pred_date],
                        y=[predicted_price],
                        mode='markers',
                        name='Prediksi',
                        marker=dict(color='red', size=15, symbol='star')
                    ),
                    row=1, col=1
                )

                # Plot volume
                fig.add_trace(
                    go.Bar(
                        x=data['Date'],
                        y=data['Volume'],
                        name='Volume',
                        marker_color='gray',
                        opacity=0.5
                    ),
                    row=2, col=1
                )

                fig.update_layout(
                    height=600,
                    showlegend=True,
                    hovermode='x unified'
                )

                st.plotly_chart(fig, use_container_width=True)

                # Analisis tambahan
                st.subheader("📊 Analisis Prediksi")

                if change > 0:
                    st.success(f"📈 **REKOMENDASI: BELI** - Harga diprediksi naik {pct_change:.2f}%")
                    st.info("""
                    **Analisis:**
                    - Momentum positif terdeteksi
                    - Potensi keuntungan jangka pendek
                    - Pertimbangkan untuk masuk dengan posisi kecil terlebih dahulu
                    """)
                else:
                    st.warning(f"📉 **REKOMENDASI: TUNGGU/JUAL** - Harga diprediksi turun {abs(pct_change):.2f}%")
                    st.info("""
                    **Analisis:**
                    - Tekanan jual mungkin masih berlanjut
                    - Tunggu konfirmasi reversal sebelum masuk
                    - Jika memegang, pertimbangkan cut loss
                    """)

else:
    st.header("🎯 Input Manual")
    st.markdown("Masukkan data harga saham terakhir untuk mendapatkan prediksi:")

    col1, col2, col3, col4, col5 = st.columns(5)

    with col1:
        open_price = st.number_input("Open", min_value=0.0, value=1000.0, step=1.0)
    with col2:
        high_price = st.number_input("High", min_value=0.0, value=1050.0, step=1.0)
    with col3:
        low_price = st.number_input("Low", min_value=0.0, value=980.0, step=1.0)
    with col4:
        close_price = st.number_input("Close", min_value=0.0, value=1025.0, step=1.0)
    with col5:
        volume = st.number_input("Volume", min_value=0, value=1000000, step=10000)

    if st.button("🔮 Prediksi dari Input Manual", type="primary"):
        features = np.array([[open_price, high_price, low_price, close_price, volume]])
        predicted_price = predict_price(features)

        st.success(f"**Prediksi Harga Besok: Rp {predicted_price:,.2f}**")

        change = predicted_price - close_price
        pct_change = (change / close_price) * 100

        st.metric(
            label="Perubahan dari Close",
            value=f"Rp {change:,.2f}",
            delta=f"{pct_change:+.2f}%"
        )

# Informasi tambahan
st.sidebar.markdown("---")
st.sidebar.header("ℹ️ Informasi")
st.sidebar.info("""
**Cara Penggunaan:**
1. Pilih mode prediksi
2. Untuk otomatis: sistem akan mengambil data terbaru
3. Untuk manual: input data terakhir
4. Klik tombol prediksi

**Model yang digunakan:**
- XGBoost dengan Chaotic PSO
- Data training: 2021-2025
- Fitur: Open, High, Low, Close, Volume
""")

st.sidebar.warning("""
**Disclaimer:**
Prediksi ini hanya untuk tujuan edukasi.
Keputusan investasi sepenuhnya menjadi tanggung jawab pengguna.
""")

# Footer
st.markdown("---")
st.caption("© 2024 Aplikasi Prediksi Saham BRIS | Model: XGBoost-CPSO")